### ISSUE TITLE
Settings don't appear in the Extensions Module

### ISSUE THREAD

**Issue by teebling** [AlfredoRamos/phpbb-ext-lazy-load#8]
Can't see the settings module in ACP > Extensions on phpBB 3.3.

Everything else seems to install properly (I can see the ext's CSS, JS etc. in the HTML), just can't adjust any settings because the module isn't there.

Can I change settings manually by editing a config file?

EDIT: Everything else works as intended, including the lazyloading itself.. just confused because the docs say there is a Settings page and I can't find it.

**Comment by AlfredoRamos** [comment]
Hi @teebling :wave: 

> can't adjust any settings because the module isn't there

Yep, It doesn't have a configuration page in the ACP because it doesn't need one.

> just confused because the docs say there is a Settings page and I can't find it

Sorry for the confusion, it's a copy&paste issue, I didn't expect someone would actually use it :grin: because I made it for self use.

I'll edit the README.
